blueprint: page

title: Événement

columns:
  - width: 1/3
    fields:
      event_date:
        type: date
        label: Date
      event_time:
        type: time
        label: Horaire
      event_type:
        type: select
        label: Type d'événement
        options:
          concert: Concerts
          table-ronde: Rencontres
          autre: Autres événements
      event_location:
        type: text
        label: Lieu
      event_ticket_link:
        type: link
        label: Lien vers la billetterie
        help: Lien vers la page de réservation ou d'achat de billets
  - width: 2/3
    fields:
      event_cover:
        type: files
        label: Image de couverture
        multiple: false
        query: page.images
        uploads: true
        width: 1/3
      event_description:
        type: writer
        label: Description
      event_gallery:
        type: files
        label: Galerie
        help: Photos supplémentaires affichées dans la section "Galerie" de la page de l'événement
        query: page.images
        uploads: true
        layout: cards
