blueprint: page

title: Fiche Enseignant·e·x & Responsable·x

columns:
  main:
    width: 2/3
    sections:
      teachers:
        type: fields
        fields:
          teachers_fonction:
            type: tags
            label: Fonction
            options:
              - enseignant·e·x
              - Équipe Administrative
          teachers_photo:
            type: files
            label: Photo
            multiple: false
            query: page.images
            uploads: true
          teachers_bio:
            type: writer
            label: Présentation
          teachers_website:
            type: url
            label: Site web
