blueprint: block
name: CtA
icon: alert
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    width: 1/2
    nodes:
      - paragraph
    marks:
      - italic
    help: Titre de la section

  description:
    type: writer
    label: Description
    inline: true
    nodes:
      - paragraph
    marks:
      - italic

  link:
    type: object
    label: Bouton
    help: Url et texte du bouton
    fields:
      link_url:
        type: link
        label: Lien
      link_text:
        type: text
        label: Texte du bouton

