blueprint: block
name: Puce
icon: list-bullet
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    nodes:
      - paragraph
    marks:
      - bold
      - italic

  text:
    type: writer
    label: Texte
    inline: false
    nodes:
      - paragraph
      - bulletList
      - orderedList
    marks:
      - bold
      - italic

  tags:
    type: tags
    label: Tags
