blueprint: block
name: Toggle
icon: angle-down
preview: fields
wysiwyg: true

fields:
  title:
    type: writer
    label: Titre
    inline: true
    width: 1/2
    nodes:
      - paragraph
    marks:
      - italic
    help: Titre de la section

  items:
    label: Items
    type: structure
    fields:
      titre:
        label: Titre
        type: text
      contenu:
        label: Contenu
        type: writer

  link:
    type: object
    label: Lien
    help: Url et texte du lien affiché à côté du titre (optionnel)
    fields:
      link_url:
        type: link
        label: Lien
      link_text:
        type: text
        label: Texte du lien
